# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71769e257c0a34e155e80f44de418a004e63da4d98abaadfb53599aa476bb2db7b8e71415c3ba47dc8e56ad2c293ef265976931c9e281d81a84ef2baaa20989e

test:
  secret_key_base: 741718f26e52b6003c6d639ac494f12a83f9277840db6bc656c384c316c3e2c8df49fb650de062eccbbdb81af04d7142d3d87b10ec8db1cfa9f11f84db07c647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
